version: "3.9"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: serbizyu
      MYSQL_USER: sail
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mailpit:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

  meilisearch:
    image: getmeili/meilisearch:v1.8
    ports:
      - "7700:7700"
    command: ["meilisearch", "--env=development"]

volumes:
  mysql_data:
